### ISSUE TITLE
const should take precedence over other keywords

### ISSUE THREAD

**Issue by magicmatatjahu** [Redocly/openapi-sampler#124]
Hello! I have schema like here:

```yaml
    arrayValueRank:
      description: >
        This Attribute indicates whether the val Attribute of the datapoint is an
        array and how many dimensions the array has.
      type: integer
      default: -1
      examples:
        - 2
      oneOf:
        - const: -1
          description: 'Scalar: The value is not an array.'
        - const: 0
          description: 'OneOrMoreDimensions: The value is an array with one or more dimensions.'
        - const: 1
          description: 'OneDimension: The value is an array with one dimension.'
        - const: 2
          description: 'The value is an array with two dimensions.'

    arrayArrayDimensions:
      type: array
      items:
        type: integer
        minimum: 0
      examples:
        - [3, 5]
```

and then the example should look like:

```yaml
              "valueRank": 2,
              "arrayDimensions": [
                3,
                5
              ],
```

but package produces:

```yaml
              "valueRank": -1,
              "arrayDimensions": [
                3,
                5
              ],
```

So I see two bugs there:
- `const` should take precedence over other keywords. At the moment package infer examples in order: `default` -> `const` -> `enum` -> `examples[0]` -> generate example using format, but I think that `const` should take precedence over other keywords.
- if schema has defined `examples`, `default`, `const` with `oneOf` like in schema above, package should infer examples from root schema, not from first `oneOf` item -> problem with [this line](https://github.com/Redocly/openapi-sampler/blob/master/src/traverse.js#L73). This problem should be also handled for other combined keywords like `allOf`.

The package is very helpful in our project and fixing this problem itself should not be difficult :) Thanks!
