### ISSUE TITLE
maxProperties not respected in generated sample

### ISSUE THREAD

**Issue by adamaltman** [Redocly/openapi-sampler#157]
Minimal schema example (example includes both properties instead of max both equal to 1).

```
type: object
    minProperties: 1
    maxProperties: 1
    properties:
      quantity:
        type: integer
        description: Usage limit quantity.
        minimum: 1
      amount:
        type: number
        format: double
        description: Usage limit amount in the currency of the order.
        minimum: 0.01
```

In this case since there is a maxProperties value of one I would expect it to return the first property in the sample.
